-- Auto-generated by an earlier `prisma migrate dev` run to drop defaults
-- on `Candidate.tags` and `Candidate.featuredSkills`. Wrapped in a guard
-- because the columns don't yet exist at this point on a fresh DB — the
-- next migration (`20260526140000_…`) creates them. On the live dev DB
-- this had already run against the existing columns, so the guard
-- preserves migration history without breaking shadow-DB replay.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'Candidate' AND column_name = 'tags'
  ) THEN
    ALTER TABLE "Candidate"
      ALTER COLUMN "featuredSkills" DROP DEFAULT,
      ALTER COLUMN "tags" DROP DEFAULT;
  END IF;
END $$;
